import './globals.css';
import type { Metadata } from 'next';
import Footer from '../components/layout/footer';
import Navbar from '@/components/layout/navbar';

export const metadata: Metadata = {
	title: 'Viva',
	description: 'Generated by Viva',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={'bg-black'}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
